name: auto-approve

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: true

jobs:
  approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # 👉 For manual run
      - name: Auto approve (manual)
        if: github.event_name == 'workflow_dispatch'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.inputs.pr_number }}

      # 👉 For PR event
      - name: Auto approve (PR event)
        if: github.event_name == 'pull_request'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
